Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PARCIAL1.Data;
using PARCIAL1.Models;
using PARCIAL1.Services;


namespace PARCIAL1.Controllers
{
    public class EmpleadosController : Controller
    {
        private readonly IEmpleadosService _empleadosService;
        private object empleadosView;
      

        public EmpleadosController( IEmpleadosService empleadosService)
        {
           _empleadosService=empleadosService;
        }
        
        // GET: Empleados
      //     public IActionResult Index()
      //  {
      //      var list = _empleadosService.GetAll();
      //      
      //      return View(list);
      //  }
           public IActionResult Index(string buscar)
        {
           
           var list=_empleadosService.GetAll(buscar);
           return View (list);
        }


        // GET: Empleados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleados = _empleadosService.GetById(id.Value);
            if (empleados == null)
            {
                return NotFound();
            }

            return View(empleados);
        }

        // GET: Empleados/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Empleados/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name,apellido,edad,sueldo,Ambiguedad")] Empleados empleados)
        {
            if (ModelState.IsValid)
            {
           
                _empleadosService.Create(empleados);    
                return RedirectToAction(nameof(Index));
            }
            return View(empleados);
        }

        // GET: Empleados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var empleados = _empleadosService.GetById(id.Value);
            if (empleados == null)
            {
                return NotFound();
            }
            return View(empleados);
        }

        // POST: Empleados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,name,apellido,edad,sueldo,Ambiguedad")] Empleados empleados)
        {
            if (id != empleados.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _empleadosService.Update(empleados);
                return RedirectToAction(nameof(Index));
            }
            return View(empleados);
        }

     //   public IActionResult CalcularSueldo(int? id)
     //   {
     //        if (id == null )
     //       {
     //           return NotFound();
     //       }
//
     //       var empleados = _empleadosService.GetById(id.Value);
     //       if (empleados == null)
     //       {
     //           return NotFound();
     //       }
//
     //       var viewModel = new EmpleadosSueldoViewModel{
     //           id=empleados.id,
     //           name=empleados.name,
     //           sueldo=empleados.sueldo
     //       };
     //       return View(viewModel);
     //   }
//
     //   [HttpPost]
     //   [ValidateAntiForgeryToken]
     //   public IActionResult CalcularSueldo(EmpleadosSueldoViewModel model)
     //   {
     //       return View();
     //   }

        // GET: Empleados/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var empleados= _empleadosService.GetById(id.Value);
            if (empleados == null)
            {
                return NotFound();
            }
            
            return View(empleados);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (id == null)
            {
                return NotFound(); 
            }
            var empleados = _empleadosService.GetById(id);
            if (empleados != null)
            {
               _empleadosService.Delete(empleados);
            }
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadosExists(int id)
        {
          return (_empleadosService.GetById(id) !=null);
        }
    }
}

Controllers/PuestosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PARCIAL1.Data;
using PARCIAL1.Models;
using PARCIAL1.Services;

namespace PARCIAL1.Controllers
{
    public class PuestosController : Controller
    {

        private readonly IPuestosService _puestosService;
        private object  puestosView;
        private readonly object puestos;

        public PuestosController(IPuestosService puestosService)
        {
           _puestosService=puestosService;
        }

        // GET: Puestos
         public IActionResult Index(string buscar)
        {
           
           var list=_puestosService.GetAll(buscar);
           return View (list);
        }

        // GET: Puestos/Details/5
       public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var puestos = _puestosService.GetById(id.Value);
            if (puestos == null)
            {
                return NotFound();
            }

            return View(puestos);
        }

        // GET: Puestos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Puestos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,EmpleadoId,puesto,sector")] Puestos puestos)
        {
            if (ModelState.IsValid)
            {
                  _puestosService.Create(puestos);    
                return RedirectToAction(nameof(Index));
            }
           
            return View(puestos);
        }

        // GET: Puestos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            
            var empleados = _puestosService.GetById(id.Value);
            if (puestos == null)
            {
                return NotFound();
            }
            return View(puestos);
        }

        // POST: Puestos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,EmpleadoId,puesto,sector")] Puestos puestos)
        {
            if (id != puestos.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                  _puestosService.Update(puestos);
                return RedirectToAction(nameof(Index));
            }
            
            return View(puestos);
        }

        // GET: Puestos/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var puestos = _puestosService.GetById(id.Value);
             
            if (puestos == null)
            {
                return NotFound();
            }

            return View(puestos);
        }

        // POST: Puestos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var puestos = _puestosService.GetById(id);
            if (puestos != null)
            {
               _puestosService.Delete(puestos);
            }
        
            return RedirectToAction(nameof(Index));
        }

        private bool PuestosExists(int id)
        {
          return (_puestosService.GetById(id) !=null);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PARCIAL1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PARCIAL1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PARCIAL1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Empleados" asp-action="Index">Empleados</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Puestos" asp-action="index">Puestos</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="roles" asp-action="index">Ver
                                Roles</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PARCIAL1  - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>